apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: hello-world
        image: yurifl/hello_world:latest
        ports:
        - containerPort: 8080
        env:
        - name: HELLO
          valueFrom:
            configMapKeyRef:
              name: hello-world
              key: hello
